name: Run Tests with Coverage in Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t fizzbuzz-app .

      - name: Run tests with coverage
        run: docker run fizzbuzz-app

      - name: Generate coverage report
        run: docker run fizzbuzz-app coverage report -m
