name: Run FizzBuzz with Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker --version

      - name: Build Docker image
        run: docker build -t fizzbuzz-app .

      - name: Run tests inside Docker
        run: docker run fizzbuzz-app coverage run -m unittest test_fizzbuzz.py

      - name: Generate coverage report
        run: docker run fizzbuzz-app coverage report -m
